package hibernate;

@Entity
public class Students {

    @Id
    // to handle autoincrement we use @GeneratedValue annotation
    // Id is auto-generated by the database (auto_increment)
    // Hibernate uses GenerationType.IDENTITY. :
    // - DB generates ID during INSERT
    // - Hibernate fetches it back and sets it into the object.
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int studentId;

    private String name;

    private int marks;

    public Students(int studentId, String name, int marks) {
        super();
        this.studentId = studentId;
        this.name = name;
        this.marks = marks;
    }

    public Students() {

    }

    // This is an intermediate Constructor, which is useful when if we use autoincrement with id,
    // then there is no need of passing id while creating the object.
    public Students(String name, int marks) {
        super();
        this.name = name;
        this.marks = marks;
    }

    public int getStudentId() {
        return studentId;
    }

    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getMarks() {
        return marks;
    }

    public void setMarks(int marks) {
        this.marks = marks;
    }

    // also include a toString method , which helps in instead of printing hashcode
    // we can get the exact values getting printed.
}
